# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpcpb import add_pb2 as add__pb2


class DocumentValidationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateDocument = channel.unary_unary(
                '/grpc.DocumentValidation/ValidateDocument',
                request_serializer=add__pb2.DocumentRequest.SerializeToString,
                response_deserializer=add__pb2.DocumentResponse.FromString,
                )


class DocumentValidationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentValidationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateDocument,
                    request_deserializer=add__pb2.DocumentRequest.FromString,
                    response_serializer=add__pb2.DocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.DocumentValidation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DocumentValidation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.DocumentValidation/ValidateDocument',
            add__pb2.DocumentRequest.SerializeToString,
            add__pb2.DocumentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
