# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: add.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tadd.proto\x12\x04grpc\"1\n\x0f\x44ocumentRequest\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\"9\n\x10\x44ocumentResponse\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x15\n\rresponse_code\x18\x02 \x01(\x05\x32W\n\x12\x44ocumentValidation\x12\x41\n\x10ValidateDocument\x12\x15.grpc.DocumentRequest\x1a\x16.grpc.DocumentResponseB\tZ\x07grpcpb/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'add_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007grpcpb/'
  _globals['_DOCUMENTREQUEST']._serialized_start=19
  _globals['_DOCUMENTREQUEST']._serialized_end=68
  _globals['_DOCUMENTRESPONSE']._serialized_start=70
  _globals['_DOCUMENTRESPONSE']._serialized_end=127
  _globals['_DOCUMENTVALIDATION']._serialized_start=129
  _globals['_DOCUMENTVALIDATION']._serialized_end=216
# @@protoc_insertion_point(module_scope)
